namespace :template do

    cwd = File.expand_path(File.dirname(__FILE__))

    desc "Bootstrap template"
    task :bootstrap do
        puts "===> Bootstrapping - plugin: template..."
        ['template:configure', 'template:build', 'template:install'].each do |subtask|
            Rake::Task[subtask].invoke
        end
        puts "===> Bootstrapping - plugin: template... done"
    
    end

    desc "Configure template"
    task :configure do
        puts "===> Configuring - plugin: template..."
        sh "cd #{cwd} && ./configure --prefix=#{$AGENT_INSTALL_DIR} --with-optimize=3 --with-libsymbiot-base-dir=#{$LIB_INSTALL_DIR}"
        puts "===> Configuring - plugin: template... done"
    end

    desc "Build template"
    task :build do
        puts "===> Compiling - plugin: template..."
        sh "cd #{cwd} && make"
        puts "===> Compiling - plugin: template... done"
    end
    
    desc "Clean template"
    task :clean do
        puts "===> Cleaning - plugin: template..."
        sh "cd #{cwd} && make distclean"
        puts "===> Cleaning - plugin: template... done"
    end
    
    desc "Install template"
    task :install do
        puts "===> Installing - plugin: template..."
        sh "cd #{cwd} && make install"
        puts "===> Installing - plugin: template... done"
    end

end
