#!/bin/bash

######################################################################
# AgentSDK - build script, generated by Ant

# libsymbiot libraries will be installed into LIB_INSTALL_DIR/lib
# libsymbiot header files will be installed into LIB_INSTALL_DIR/include

LIB_INSTALL_DIR="/usr/local"

# Agent binaries will be installed into AGENT_INSTALL_DIR/bin

AGENT_INSTALL_DIR="/usr/local"

# Logs will be created LOG_DIR; that directory will be created
# on-the-fly if necessary when the first log entry is written

LOG_DIR="/var/log/opensims"

# Configuration base directory.

CONF_DIR="/etc/opensims"

# The name of the appliance/server

#SERVERNAME=`hostname`
SERVERNAME="im5600.symbiot.com"

# INSTALL_STARTUP_SCRIPTS determines if startup scripts are automatically
# installed (1), or not (0).

INSTALL_STARTUP_SCRIPTS=1

SCRIPT=$0
ORIG=$PWD
ROOT=`dirname $SCRIPT`

######################################################################
# main entry point

if [ "$#" -lt 1 ]
then
    echo "ERROR: not enough args"
    exit 1
fi

for arg in $*
do


if test "$arg" = "autoconf"; then
echo "====> Generating configuration scripts - library: libsymbiot ..."
cd $ORIG
cd $ROOT/library/.
autoheader || exit 1
autoconf || exit 1
echo "====> Generating configuration scripts - library: libsymbiot ..." "done"
fi

if test "$arg" = "configure"; then
echo "====> Configuring - library: libsymbiot ..."
cd $ORIG
cd $ROOT/library/.
./configure --prefix=$LIB_INSTALL_DIR --with-local-expat --with-optimize=3 --with-log-dir=$LOG_DIR --with-conf-dir=$CONF_DIR --with-server=$SERVERNAME || exit 1
echo "====> Configuring - library: libsymbiot ..." "done"
fi

if test "$arg" = "lib-compile"; then
echo "====> Compiling - library: libsymbiot ..."
cd $ORIG
cd $ROOT/library/.
make || exit 1
echo "====> Compiling - library: libsymbiot ..." "done"
fi

if test "$arg" = "lib-install"; then
echo "====> Installing (requires root user) - library: libsymbiot ..."
cd $ORIG
cd $ROOT/library/.
make install || exit 1
echo "====> Installing (requires root user) - library: libsymbiot ..." "done"
fi

if test "$arg" = "clean"; then
echo "====> Cleaning - library: libsymbiot ..."
cd $ORIG
cd $ROOT/library/.
make distclean || exit 1
echo "====> Cleaning - library: libsymbiot ..." "done"
fi

if test "$arg" = "autoconf"; then
echo "====> Generating configuration scripts - agent: symagent ..."
cd $ORIG
cd $ROOT/agents/symagent
autoheader || exit 1
autoconf || exit 1
echo "====> Generating configuration scripts - agent: symagent ..." "done"
fi

if test "$arg" = "configure"; then
echo "====> Configuring - agent: symagent ..."
cd $ORIG
cd $ROOT/agents/symagent
./configure --prefix=$AGENT_INSTALL_DIR --with-optimize=3 --with-libsymbiot-base-dir=$LIB_INSTALL_DIR || exit 1
echo "====> Configuring - agent: symagent ..." "done"
fi

if test "$arg" = "compile"; then
echo "====> Compiling - agent: symagent ..."
cd $ORIG
cd $ROOT/agents/symagent
LD_RUN_PATH=$LIB_INSTALL_DIR/lib make || exit 1
echo "====> Compiling - agent: symagent ..." "done"
fi

if test "$arg" = "install"; then
echo "====> Installing (requires root user) - agent: symagent ..."
cd $ORIG
cd $ROOT/agents/symagent
make install || exit 1
echo "====> Installing (requires root user) - agent: symagent ..." "done"
fi

if test "$arg" = "clean"; then
echo "====> Cleaning - agent: symagent ..."
cd $ORIG
cd $ROOT/agents/symagent
make distclean || exit 1
echo "====> Cleaning - agent: symagent ..." "done"
fi

if test "$arg" = "script-install"; then
echo "====> Installing startup scripts (requires root user) - agent: symagent ..."
cd $ORIG
cd $ROOT/agents/symagent
if test $INSTALL_STARTUP_SCRIPTS = 1; then
    make install-startup-script || exit 1
fi
echo "====> Installing startup scripts (requires root user) - agent: symagent ..." "done"
fi

if test "$arg" = "autoconf"; then
echo "====> Generating configuration scripts - plugin: effector ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/effector
autoheader || exit 1
autoconf || exit 1
echo "====> Generating configuration scripts - plugin: effector ..." "done"
fi

if test "$arg" = "configure"; then
echo "====> Configuring - plugin: effector ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/effector
./configure --prefix=$AGENT_INSTALL_DIR --with-optimize=3 --with-libsymbiot-base-dir=$LIB_INSTALL_DIR || exit 1
echo "====> Configuring - plugin: effector ..." "done"
fi

if test "$arg" = "compile"; then
echo "====> Compiling - plugin: effector ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/effector
LD_RUN_PATH=$LIB_INSTALL_DIR/lib make || exit 1
echo "====> Compiling - plugin: effector ..." "done"
fi

if test "$arg" = "install"; then
echo "====> Installing (requires root user) - plugin: effector ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/effector
make install || exit 1
echo "====> Installing (requires root user) - plugin: effector ..." "done"
fi

if test "$arg" = "clean"; then
echo "====> Cleaning - plugin: effector ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/effector
make distclean || exit 1
echo "====> Cleaning - plugin: effector ..." "done"
fi

if test "$arg" = "autoconf"; then
echo "====> Generating configuration scripts - plugin: log-watcher ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/log-watcher
autoheader || exit 1
autoconf || exit 1
echo "====> Generating configuration scripts - plugin: log-watcher ..." "done"
fi

if test "$arg" = "configure"; then
echo "====> Configuring - plugin: log-watcher ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/log-watcher
./configure --prefix=$AGENT_INSTALL_DIR --with-optimize=3 --with-libsymbiot-base-dir=$LIB_INSTALL_DIR || exit 1
echo "====> Configuring - plugin: log-watcher ..." "done"
fi

if test "$arg" = "compile"; then
echo "====> Compiling - plugin: log-watcher ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/log-watcher
LD_RUN_PATH=$LIB_INSTALL_DIR/lib make || exit 1
echo "====> Compiling - plugin: log-watcher ..." "done"
fi

if test "$arg" = "install"; then
echo "====> Installing (requires root user) - plugin: log-watcher ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/log-watcher
make install || exit 1
echo "====> Installing (requires root user) - plugin: log-watcher ..." "done"
fi

if test "$arg" = "clean"; then
echo "====> Cleaning - plugin: log-watcher ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/log-watcher
make distclean || exit 1
echo "====> Cleaning - plugin: log-watcher ..." "done"
fi

if test "$arg" = "autoconf"; then
echo "====> Generating configuration scripts - plugin: mac-lookup ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/mac-lookup
autoheader || exit 1
autoconf || exit 1
echo "====> Generating configuration scripts - plugin: mac-lookup ..." "done"
fi

if test "$arg" = "configure"; then
echo "====> Configuring - plugin: mac-lookup ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/mac-lookup
./configure --prefix=$AGENT_INSTALL_DIR --with-optimize=3 --with-libsymbiot-base-dir=$LIB_INSTALL_DIR || exit 1
echo "====> Configuring - plugin: mac-lookup ..." "done"
fi

if test "$arg" = "compile"; then
echo "====> Compiling - plugin: mac-lookup ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/mac-lookup
LD_RUN_PATH=$LIB_INSTALL_DIR/lib make || exit 1
echo "====> Compiling - plugin: mac-lookup ..." "done"
fi

if test "$arg" = "install"; then
echo "====> Installing (requires root user) - plugin: mac-lookup ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/mac-lookup
make install || exit 1
echo "====> Installing (requires root user) - plugin: mac-lookup ..." "done"
fi

if test "$arg" = "clean"; then
echo "====> Cleaning - plugin: mac-lookup ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/mac-lookup
make distclean || exit 1
echo "====> Cleaning - plugin: mac-lookup ..." "done"
fi

if test "$arg" = "autoconf"; then
echo "====> Generating configuration scripts - plugin: network ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/network
autoheader || exit 1
autoconf || exit 1
echo "====> Generating configuration scripts - plugin: network ..." "done"
fi

if test "$arg" = "configure"; then
echo "====> Configuring - plugin: network ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/network
./configure --prefix=$AGENT_INSTALL_DIR --with-optimize=3 --with-libsymbiot-base-dir=$LIB_INSTALL_DIR || exit 1
echo "====> Configuring - plugin: network ..." "done"
fi

if test "$arg" = "compile"; then
echo "====> Compiling - plugin: network ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/network
LD_RUN_PATH=$LIB_INSTALL_DIR/lib make || exit 1
echo "====> Compiling - plugin: network ..." "done"
fi

if test "$arg" = "install"; then
echo "====> Installing (requires root user) - plugin: network ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/network
make install || exit 1
echo "====> Installing (requires root user) - plugin: network ..." "done"
fi

if test "$arg" = "clean"; then
echo "====> Cleaning - plugin: network ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/network
make distclean || exit 1
echo "====> Cleaning - plugin: network ..." "done"
fi

if test "$arg" = "autoconf"; then
echo "====> Generating configuration scripts - plugin: nmap ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/nmap
autoheader || exit 1
autoconf || exit 1
echo "====> Generating configuration scripts - plugin: nmap ..." "done"
fi

if test "$arg" = "configure"; then
echo "====> Configuring - plugin: nmap ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/nmap
./configure --prefix=$AGENT_INSTALL_DIR --with-optimize=3 --with-libsymbiot-base-dir=$LIB_INSTALL_DIR || exit 1
echo "====> Configuring - plugin: nmap ..." "done"
fi

if test "$arg" = "compile"; then
echo "====> Compiling - plugin: nmap ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/nmap
LD_RUN_PATH=$LIB_INSTALL_DIR/lib make || exit 1
echo "====> Compiling - plugin: nmap ..." "done"
fi

if test "$arg" = "install"; then
echo "====> Installing (requires root user) - plugin: nmap ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/nmap
make install || exit 1
echo "====> Installing (requires root user) - plugin: nmap ..." "done"
fi

if test "$arg" = "clean"; then
echo "====> Cleaning - plugin: nmap ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/nmap
make distclean || exit 1
echo "====> Cleaning - plugin: nmap ..." "done"
fi

if test "$arg" = "autoconf"; then
echo "====> Generating configuration scripts - plugin: processes ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/processes
autoheader || exit 1
autoconf || exit 1
echo "====> Generating configuration scripts - plugin: processes ..." "done"
fi

if test "$arg" = "configure"; then
echo "====> Configuring - plugin: processes ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/processes
./configure --prefix=$AGENT_INSTALL_DIR --with-optimize=3 --with-libsymbiot-base-dir=$LIB_INSTALL_DIR || exit 1
echo "====> Configuring - plugin: processes ..." "done"
fi

if test "$arg" = "compile"; then
echo "====> Compiling - plugin: processes ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/processes
LD_RUN_PATH=$LIB_INSTALL_DIR/lib make || exit 1
echo "====> Compiling - plugin: processes ..." "done"
fi

if test "$arg" = "install"; then
echo "====> Installing (requires root user) - plugin: processes ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/processes
make install || exit 1
echo "====> Installing (requires root user) - plugin: processes ..." "done"
fi

if test "$arg" = "clean"; then
echo "====> Cleaning - plugin: processes ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/processes
make distclean || exit 1
echo "====> Cleaning - plugin: processes ..." "done"
fi

if test "$arg" = "autoconf"; then
echo "====> Generating configuration scripts - plugin: snort-log ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/snort-log
autoheader || exit 1
autoconf || exit 1
echo "====> Generating configuration scripts - plugin: snort-log ..." "done"
fi

if test "$arg" = "configure"; then
echo "====> Configuring - plugin: snort-log ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/snort-log
./configure --prefix=$AGENT_INSTALL_DIR --with-optimize=3 --with-libsymbiot-base-dir=$LIB_INSTALL_DIR || exit 1
echo "====> Configuring - plugin: snort-log ..." "done"
fi

if test "$arg" = "compile"; then
echo "====> Compiling - plugin: snort-log ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/snort-log
LD_RUN_PATH=$LIB_INSTALL_DIR/lib make || exit 1
echo "====> Compiling - plugin: snort-log ..." "done"
fi

if test "$arg" = "install"; then
echo "====> Installing (requires root user) - plugin: snort-log ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/snort-log
make install || exit 1
echo "====> Installing (requires root user) - plugin: snort-log ..." "done"
fi

if test "$arg" = "clean"; then
echo "====> Cleaning - plugin: snort-log ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/snort-log
make distclean || exit 1
echo "====> Cleaning - plugin: snort-log ..." "done"
fi

if test "$arg" = "autoconf"; then
echo "====> Generating configuration scripts - plugin: tester ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/tester
autoheader || exit 1
autoconf || exit 1
echo "====> Generating configuration scripts - plugin: tester ..." "done"
fi

if test "$arg" = "configure"; then
echo "====> Configuring - plugin: tester ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/tester
./configure --prefix=$AGENT_INSTALL_DIR --with-optimize=3 --with-libsymbiot-base-dir=$LIB_INSTALL_DIR || exit 1
echo "====> Configuring - plugin: tester ..." "done"
fi

if test "$arg" = "compile"; then
echo "====> Compiling - plugin: tester ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/tester
LD_RUN_PATH=$LIB_INSTALL_DIR/lib make || exit 1
echo "====> Compiling - plugin: tester ..." "done"
fi

if test "$arg" = "install"; then
echo "====> Installing (requires root user) - plugin: tester ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/tester
make install || exit 1
echo "====> Installing (requires root user) - plugin: tester ..." "done"
fi

if test "$arg" = "clean"; then
echo "====> Cleaning - plugin: tester ..."
cd $ORIG
cd $ROOT/agents/symagent/plugins/tester
make distclean || exit 1
echo "====> Cleaning - plugin: tester ..." "done"
fi

done

######################################################################
# put us back where we started

cd $ORIG
echo "====> Build Finished"
