namespace :logwatcher do

    cwd = File.expand_path(File.dirname(__FILE__))

    desc "Bootstrap logwatcher"
    task :bootstrap do
        puts "===> Bootstrapping - plugin: logwatcher..."
        ['logwatcher:configure', 'logwatcher:build', 'logwatcher:install'].each do |subtask|
            Rake::Task[subtask].invoke
        end
        puts "===> Bootstrapping - plugin: logwatcher... done"
    
    end

    desc "Configure logwatcher"
    task :configure do
        puts "===> Configuring - plugin: logwatcher..."
        sh "cd #{cwd} && ./configure --prefix=#{$AGENT_INSTALL_DIR} --with-optimize=3 --with-libsymbiot-base-dir=#{$LIB_INSTALL_DIR}"
        puts "===> Configuring - plugin: logwatcher... done"
    end

    desc "Build logwatcher"
    task :build do
        puts "===> Compiling - plugin: logwatcher..."
        sh "cd #{cwd} && make"
        puts "===> Compiling - plugin: logwatcher... done"
    end
    
    desc "Clean logwatcher"
    task :clean do
        puts "===> Cleaning - plugin: logwatcher..."
        sh "cd #{cwd} && make distclean"
        puts "===> Cleaning - plugin: logwatcher... done"
    end
    
    desc "Install logwatcher"
    task :install do
        puts "===> Installing - plugin: logwatcher..."
        sh "cd #{cwd} && make install"
        puts "===> Installing - plugin: logwatcher... done"
    end

end
