namespace :processes do

    cwd = File.expand_path(File.dirname(__FILE__))

    desc "Bootstrap processes"
    task :bootstrap do
        puts "===> Bootstrapping - plugin: processes..."
        ['processes:configure', 'processes:build', 'processes:install'].each do |subtask|
            Rake::Task[subtask].invoke
        end
        puts "===> Bootstrapping - plugin: processes... done"
    
    end

    desc "Configure processes"
    task :configure do
        puts "===> Configuring - plugin: processes..."
        sh "cd #{cwd} && ./configure --prefix=#{$AGENT_INSTALL_DIR} --with-optimize=3 --with-libsymbiot-base-dir=#{$LIB_INSTALL_DIR}"
        puts "===> Configuring - plugin: processes... done"
    end

    desc "Build processes"
    task :build do
        puts "===> Compiling - plugin: processes..."
        sh "cd #{cwd} && make"
        puts "===> Compiling - plugin: processes... done"
    end
    
    desc "Clean processes"
    task :clean do
        puts "===> Cleaning - plugin: processes..."
        sh "cd #{cwd} && make distclean"
        puts "===> Cleaning - plugin: processes... done"
    end
    
    desc "Install processes"
    task :install do
        puts "===> Installing - plugin: processes..."
        sh "cd #{cwd} && make install"
        puts "===> Installing - plugin: processes... done"
    end

end
