namespace :network do

    cwd = File.expand_path(File.dirname(__FILE__))

    desc "Bootstrap network"
    task :bootstrap do
        puts "===> Bootstrapping - plugin: network..."
        ['network:configure', 'network:build', 'network:install'].each do |subtask|
            Rake::Task[subtask].invoke
        end
        puts "===> Bootstrapping - plugin: network... done"
    
    end

    desc "Configure network"
    task :configure do
        puts "===> Configuring - plugin: network..."
        sh "cd #{cwd} && ./configure --prefix=#{$AGENT_INSTALL_DIR} --with-optimize=3 --with-libsymbiot-base-dir=#{$LIB_INSTALL_DIR}"
        puts "===> Configuring - plugin: network... done"
    end

    desc "Build network"
    task :build do
        puts "===> Compiling - plugin: network..."
        sh "cd #{cwd} && make"
        puts "===> Compiling - plugin: network... done"
    end
    
    desc "Clean network"
    task :clean do
        puts "===> Cleaning - plugin: network..."
        sh "cd #{cwd} && make distclean"
        puts "===> Cleaning - plugin: network... done"
    end
    
    desc "Install network"
    task :install do
        puts "===> Installing - plugin: network..."
        sh "cd #{cwd} && make install"
        puts "===> Installing - plugin: network... done"
    end

end
