namespace :effector do

    cwd = File.expand_path(File.dirname(__FILE__))

    desc "Bootstrap effector"
    task :bootstrap do
        puts "===> Bootstrapping - plugin: effector..."
        ['effector:configure', 'effector:build', 'effector:install'].each do |subtask|
            Rake::Task[subtask].invoke
        end
        puts "===> Bootstrapping - plugin: effector... done"
    
    end

    desc "Configure effector"
    task :configure do
        puts "===> Configuring - plugin: effector..."
        sh "cd #{cwd} && ./configure --prefix=#{$AGENT_INSTALL_DIR} --with-optimize=3 --with-libsymbiot-base-dir=#{$LIB_INSTALL_DIR}"
        puts "===> Configuring - plugin: effector... done"
    end

    desc "Build effector"
    task :build do
        puts "===> Compiling - plugin: effector..."
        sh "cd #{cwd} && make"
        puts "===> Compiling - plugin: effector... done"
    end
    
    desc "Clean effector"
    task :clean do
        puts "===> Cleaning - plugin: effector..."
        sh "cd #{cwd} && make distclean"
        puts "===> Cleaning - plugin: effector... done"
    end
    
    desc "Install effector"
    task :install do
        puts "===> Installing - plugin: effector..."
        sh "cd #{cwd} && make install"
        puts "===> Installing - plugin: effector... done"
    end

end
